import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>starting tamplate next js/ts with tailwind css</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container-none w-full h-[100vh] bg-emerald-800 flex flex-col justify-center items-center gap-2">
        <h1 className="text-sky-400/90 text-4xl font-bold">
          STARTING TAMPLATE
        </h1>
        <h2 className="text-violet-400/70 text-xl font-bold">
          NEXT JS/TS WITH TAILWIND CSS
        </h2>
        <h3 className="text-slate-400 font-mono text-lg ">happy good day</h3>
      </main>
    </>
  );
}
